### ISSUE TITLE
Feature Request - Text Highlight

### ISSUE THREAD

**Issue by yashkulkarni** [crestify/crestify#11]
Crestify is doing very well but I have a few suggestion or feature request.

1. To have an option to save just text from a website and not the entire page as an image. Or even some selected data to be bookmarked on a website or highlighted. 

2. The title or heading or articles have tags and those tags should be saved in crestify's tag list as it would get easier to find the article and the website. Powerful search may save a lot of time for a lot of people. It still works fine but this might help a little bit more. 

Thanks.

**Comment by dhamaniasad** [comment]
Hey Yash!

I'll address your points here, but can you please open 1 issue per feature request? It will make it easier for us to keep track of it :). 

1. 
a) Currently we do not store a screenshot of the page. Is that something you'd like? (Feature request)
b) But we do have the readability mode, which saves cleaned text from the page
c) I think you mean this as something similar to how you can save notes or highlight text on Medium. Did I get you correctly? I think that could come in handy. (Feature request)

2. Currently we do offer a way to search through bookmarks using basic (title + description), fulltext (entire text of the page), and url (could be fragments of the url, like the domain for example). Clicking on a tag in the sidebar will get you tag based filtering for bookmarks and you can combine that will the search bar to get pretty powerful slicing and dicing of your bookmarks. I'd be very happy to hear any ideas you may have that could improve this further :)!

I'll close this issue since we'd like to open one issue per feature request. Please do that and we'll move the conversation there :).

**Comment by yashkulkarni** [comment]
Hey Asad,

I have changed the Feature Request for the text highlight part which you wrote about as it is something that I would love to see.

and for other features, I'll be lodging new feature requests. So let's meet in the new conversations there. :)

Thanks!.
