### ISSUE TITLE
A live preview?

### ISSUE THREAD

**Issue by zblesk** [crestify/crestify#16]
Do you think you could maybe create a live demo in which I could click around? (It doesn't even need to allow me to add links.) I'd like to try it out, but haven't been able to get it running myself.

**Comment by dhamaniasad** [comment]
Hey Ladislav,

Crestify is available as a hosted service at
https://www.crestify.com/register

You can use the invite code `fb` to create an account on it. If you'd
rather not host Crestify yourself, we've got this option for you :)

**Comment by zblesk** [comment]
Thank you. If it's linked somewhere in this this repo, I'd completely missed it, sorry.  
For now, this is perfect, thanks. 

If I end up using Crestify, I'd probably be interested in self-hosting, though. One of the reasons I'd started writing a similar tool myself is that I'd like to have all of those data in local copies. (I didn't get as far as you did, though, and my approach was quite different.)

**Comment by dhamaniasad** [comment]
I don't think it's linked in the repo as yet. I'll add it soon. 

We are open to new ideas, since the goal is to create the perfect bookmarking tool. Before Crestify, I had to use multiple tools to achieve the setup I wanted, which was inefficient and imperfect. Crestify exists to make sure no one has to do that again. What would you like Crestify to have that would make you want to switch to it? 

Also, since you were working on something similar yourself, you could contribute to Crestify and work on the features you're interested in. Would be happy to help you out in any way :)

**Comment by zblesk** [comment]
Yeah, I think I understand where you're coming from. I have my links spread over various services. I do export those into a local backup, but that doesn't help with link rot. That's why I started writing my own thing (in Py3).  But it's conceptually quite different - I wanted it to be a single app that I can just pip install, and have everything indexed in a local (SQLite) database. The main thing that puts me off from Crestify is the setup itself - it seems to have way more components than necessary. (Please, don't read that as an attack on your design; just that I made a design choice differently.)

However, maybe Crestify will convince me, after I've played with it a bit; if that were the case, I might try to contribute, since my mini-project would get killed immediately.

**Comment by dhamaniasad** [comment]
I think the architecture could be worth looking into. So far, we've got:
1. Postgres
2. RabbitMQ
3. Redis
4. PhantomJS
5. libxml

RabbitMQ is used as our async job queue, and we've got jobs for archiving the bookmarks in the background, to fetching their readable content, to running bookmark imports (sometimes they can take minutes). 

Redis could be eliminated. The only reason it is used is to hold tab saves for 10 minutes after they're added. We send the data to our server, and then open a Crestify page where they can name the tab collection. Since we couldn't open this URL with a POST request, we resorted to this hack. Oh, and because I wanted to use it for something :P. But Redis is one thing that can be reasonably eliminated from the stack. 

We need PhantomJS, because as more and more pages become increasingly dynamic, it becomes futile to just wget them on the server. You will end up with a link to a JavaScript file and a CSS file, but not any actual content. So we need to execute these pages on the server like a browser would, waiting for some time for scripts to execute and populate the content of the page, for which we use PhantomJS. 

libxml is another dependency that has to be installed. We use lxml with BeautifulSoup to parse the pages and extract content from them, like for the reader view feature. 

Supervisor is also mentioned in the install docs, but for running locally, rather than production, it can be safely ignored. 

We also use Fabric for deploy and install automation, which comes with dependencies of its own. And for the Vagrant image, you would need Vagrant and VirtualBox installed. But those are really only needed if you go the automated install way. 

Crestify started out as the service you see running at crestify.com, and it was open sourced later. So that has lead to the architectural decisions we went with. 

If there is anything in here that does not make sense, anything you can provide your input on, any way you think Crestify could be made better, I'm very happy to hear you :)

As for the issue, I'll keep it open until I mention the hosted service in our docs.

**Comment by Hans-Maulwurf** [comment]
is there still a live preview available? registering with the code "fb" doesnt seem to work anymore? i get no email with instructions

**Comment by dhamaniasad** [comment]
The live preview had to be taken offline. There was a billing mishap with our host, and they haphazardly deleted the instance before we could resolve the issue. There's still a backlog of issues to resolve before a live preview can be brought back online. I'll go ahead and close this issue for now.
